### ISSUE TITLE
imported OI but Robot.java not detecting

### ISSUE THREAD

**Issue by smerkousdavid** [UsaidPro/FRC-2015-Java-code#5]
Hey, i have been trying to get the commands between OI, RobotMap and Robot(Main) to work together, so I imported OI and RobotMap but it is saying that's not finding the import OI, but the weird thing is that it detects RobotMap, the weirdest part is that both are in the same package

**Comment by oliverwarne** [comment]
Im looking through it and  I don't understand why it wouldn't. Is it possible that you need to import all of the packages that OI imports in order to use it? Can't see any other reason. Coding in java is going to be so much easier because (once we're back at school) we'll just be able to ask Mrs. Bolton. It would probably be reaching, but you could send her a message.

EDIT: OI also imports Robot. Is that it?

**Comment by smerkousdavid** [comment]
I don't know ill have to see

**Comment by smerkousdavid** [comment]
I have made a temporary fix by putting in all the variables in Robot.java but then we have the problem of Magic Numbers.

EDIT: I mean Figuratively

**Comment by UsaidPro** [comment]
I noticed that too. Maybe we would have to make a subsystem which OI and Robot.java import? I think that the reason it can't be imported is because the three files "Robot.java", 'OI.java', and 'RobotMapping.java' (think that is what is called?) are separate from each other and are compiled at the same 'level' of code - meaning that they can't import each other since they are compiled around the same time. Has anyone tried compiling the entire project and just not one file?

Sorry if this makes no sense - Java is a _just a bit_ different from C++ in this :P

**Comment by smerkousdavid** [comment]
I have mabye sidetracked a little and tried to get smart dashboard working, but it is kind of crappy on java.....
